version: '2'
services:
  yacy_mcp:
    build: .
    links:
      - elasticsearch
    ports:
      - 8100:8100

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.0
    container_name: elasticsearch
    environment:
      - cluster.name=yacygrid
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    volumes:
      - /mnt/docker:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    expose:
      - "9300"
      - "9200"

    
volumes:
  esdata1:
    driver: local

